### ISSUE TITLE
Least-Squares Fitting API(s)

### ISSUE THREAD

**Issue by microbuilder** [zscilib/zscilib#22]
**Least-squares fitting**(and family) is often used to calibrate certain types of sensors (for example, magnetometers to fit an ellipse to a sphere). 

Support for the following should be added:

- [x] **Linear** least squares (best-fitting straight line through a dataset)
- [ ] **Non-linear** least-squares
- [ ] [Minimum Volume Enclosing Ellipsoid](https://es.mathworks.com/matlabcentral/fileexchange/9542-minimum-volume-enclosing-ellipsoid)
  - See also: http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.116.7691
- [x] Quadric fitting (ellipsoid and sphere, for example)

## References 

- Non-linear LSF: https://www.gnu.org/software/gsl/doc/html/nls.html
- Linear LSF: https://www.gnu.org/software/gsl/doc/html/lls.html
- [Linear or Nonlinear Least-Squares Analysis of Kinetic Data?](https://pubs.acs.org/doi/pdf/10.1021/acs.jchemed.6b00629)
- [Multi-dimensional Ellipsoidal Fitting](http://www.physics.smu.edu/~scalise/SMUpreprints/SMU-HEP-10-14.pdf)

## Use Case

A good explanation of a use case for this API is described here: https://electronics.stackexchange.com/a/22271

**Comment by microbuilder** [comment]
Closing for now since non-linear LS and min volume enclosing have too many missing dependencies to implement at this point, but linear least squares and correction functions to adjust magnetometer vector arrays have been implemented.

**Comment by jdwang001** [comment]
Hello, I'm currently porting an algorithm library to an MCU , which is implemented based on GSL (GNU Scientific Library). 
The library includes a function 
```
void polyfit(const double *xvals, const double *yvals, int n, int order, double *coeffs),
```
commonly found in NumPy and MATLAB. I'm not very familiar with ZSCLib and GSL. 
I would like to know how to proceed step by step to use polyfit in ZSCLib. 
Could you provide me with a rough idea or guidance?
